alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias c='clear'
alias cat='bat -pp'
alias eza='eza --color=always --color-scale=all --color-scale-mode=gradient --icons=always --group-directories-first'
alias ls='eza'
alias la='eza --all'
alias ll='eza --all --long --git --header'
alias m='micro'
